app_name: customer-financial-profile
connections:
  - config : !S3Storage
      details:
        access_key_id: "{{AWS_ACCESS_KEY}}"
        secret_access_key: "{{AWS_SECRET}}"
        region: 'us-west-2'
        bucket_name: credit-card-default-dozer
      tables:
        - !Table
          name: customers
          config: !CSV
            path: customer 
            extension: .csv
    name: s30


  - config : !S3Storage
      details:
        access_key_id: "{{AWS_ACCESS_KEY}}"
        secret_access_key: "{{AWS_SECRET}}"
        region: 'us-west-2'
        bucket_name: credit-card-default-dozer
      tables:
        - !Table
          name: params
          config: !CSV
            path: data # path to files or folder inside a bucket
            extension: .csv
    name: s3


sources:
        - name: scoring_table
          table_name: params
          connection: s3

        - name: personal
          table_name: customers
          connection: s30
         
sql: |
  SELECT ID as id, LIMIT_BAL as credit
  INTO credit_cache
  FROM scoring_table;
   


  
endpoints:
        - name: credit_endpt
          path: /credit
          table_name: credit_cache
