name: Run Dozer
on:
  push:
    branches:
      - main
      - dozer-cache
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install protobuf
        run: sudo apt-get install protobuf-compiler 
      - name: Caching dozer
        uses: baptiste0928/cargo-install@v2
        with:
          crate: dozer-cli
          git: https://github.com/getdozer/dozer
          features: cloud
      - name: Use access key
        run: |
          echo "Using access key: $ { { secrets.AWS_ACCESS_KEY }}"