name: Run Dozer
on:
  push:
    branches:
      - main
env:
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET: ${{ secrets.AWS_SECRET }}
jobs:
  prep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Check command
        id: check
        run: |
          if grep -q "Upd" action.txt; then
            echo "::set-output name=contains_string::Upd"
          elif grep -q "Del" action.txt; then
            echo "::set-output name=contains_string::Del"
          elif grep -q "Dep" action.txt; then
            echo "::set-output name=contains_string::Dep"
          else
            echo "::set-output name=contains_string::Wip"
          fi


  run-script:
    needs: prep
    if: ${{ !contains(github.event.head_commit.message, 'Wip') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: us-west-2
      - name: Install protobuf
        run: sudo apt-get install protobuf-compiler 
      - name: Installing dozer
        uses: baptiste0928/cargo-install@v2
        with:
          crate: dozer-cli
          git: https://github.com/getdozer/dozer
          features: cloud
          locked: true
      - name: Initialize Dozer
        run: dozer init
      - name: Log into Dozer Cloud
        run: dozer cloud login --organisation_slug dozerinternsample-xwcov --profile_name default --client_id ${{ secrets.DOZER_CLIENT_ID }} --client_secret ${{ secrets.DOZER_CLIENT_SECRET }} 
      - name: Deploy on cloud
        if: ${{ contains(github.event.head_commit.message, 'Dep') }}
        run: dozer cloud deploy -s AWS_ACCESS_KEY=${{secrets.AWS_ACCESS_KEY}} -s AWS_SECRET=${{secrets.AWS_SECRET}} -c dozer-config.yaml
      - name: Delete App
        if: ${{ contains(github.event.head_commit.message, 'Del') }}
        run: dozer cloud delete
      - name: Update App
        if: ${{ contains(github.event.head_commit.message, 'Upd') }}
        run: dozer cloud deploy -s AWS_ACCESS_KEY=${{secrets.AWS_ACCESS_KEY}} -s AWS_SECRET=${{secrets.AWS_SECRET}}
      - name: Save App ID
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Save App ID"
          file_pattern: '*.cloud.yaml'
