name: Run Dozer
on:
  push:
    branches:
      - main
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Pull Dozer
        run: git clone https://github.com/getdozer/dozer
      - name: Install protobuf
        run: sudo apt-get install protobuf-compiler 
      - name: Install Dozer
        run: cargo install --path dozer/dozer-cli --features cloud
      - name: Init
        run: dozer init && curl --create-dirs -o data/trips/fhvhv_tripdata_2022-01.parquet https://d37ci6vzurychx.cloudfront.net/trip-data/fhvhv_tripdata_2022-01.parquet
      - name: Run Dozer
        run: dozer cloud login --organisation_slug dozerinternsample-xwcov --profile_name default --client_id 5bhrickg9ee1fn3cqoikgaf7o8 --client_secret 1c8ma15um3tjsh35mouuat3emdk2ia4ohul5j48ahi3lu4m1i7lp
      - name: Run Dozer
        run: dozer deploy -c dozer-config.yaml